# Generated by Django 5.1.3 on 2025-02-17 05:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
        ('product', '0026_remove_cart_user_cart_is_paid_cart_total_amount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkout',
            name='Order',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='total_amount',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='tran_id',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='user',
        ),
        migrations.RemoveField(
            model_name='checkout',
            name='cart',
        ),
        migrations.DeleteModel(
            name='OrderdItem',
        ),
        migrations.AddField(
            model_name='checkout',
            name='cart',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='checkouts', to='product.cart'),
        ),
    ]
