# Generated by Django 5.1.3 on 2025-02-19 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0005_remove_order_cart_remove_order_quantity_order_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
