# Generated by Django 5.1.3 on 2025-02-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0007_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='cart',
        ),
        migrations.RemoveField(
            model_name='order',
            name='quantity',
        ),
    ]
