# Generated by Django 5.1.3 on 2025-02-19 09:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0008_remove_order_cart_remove_order_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='user',
        ),
    ]
